apps/urls.py
from django.urls import include, path
from django.contrib import admin



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books'))
   
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
  path('', views.BookList.as_view(), name='books_list'),
  path('new', views.BookCreate.as_view(), name='books_new'),
  path('edit/<int:pk>', views.BookUpdate.as_view(), name='books_edit'),
  path('delete/<int:pk>', views.BookDelete.as_view(), name='books_delete'),
]

books/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:books_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render

books/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from books.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books:books_list')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books:books_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:books_list')

books/templates/books/book_confirm_delete.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'books\stylesheet.css' %}">
</head>
<body class="container-fluid">
    <div class="row text-center">
            <h2 class="col-12 bg-primary text-white"><a href="{% url 'books:books_list' %}" class='text-white'>Books</a>: Delete</h2>
            <form method="post" class="col-12 p-5">{% csrf_token %}
               <p class="font"> Are you sure you want to delete "{{ object }}" ?</p><br>
                <input class="btn btn-danger align" type="submit" value="Delete" />
            </form>
    </div>

</body>
{% endblock %}

books/templates/books/book_form.html
{% block content %}
<head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body class="container-fluid">
        <div class="row text-center">
            <h2 class="col-12 bg-primary text-white"><a href="{% url 'books:books_list' %}" class='text-white'>Books</a>: Edit</h2>

            <form method="post" class="col-12 p-5">{% csrf_token %}
                <div class="font"> {{ form.as_p }} </div>
                <input class="btn btn-success" type="submit" value="Submit" />
            </form>
        </div>
</body>

{% endblock %}

books/templates/books/book_list.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body class="container-fluid text-center">
        <div class="row  text-center">
            <h2 class="col-12 bg-primary text-white"><a href="{% url 'books:books_list' %}" class='text-white'>Books</a></h2>
            <div class=" col-12 wrapper">
                <ul class="list-unstyled">
                    {% for  books in object_list %}
                    <li> <br> {{ books.name }}  ({{ books.pages }} Pages) 
                    <button class="btn btn-warning" onclick="location.href='{% url 'books:books_edit' books.id %}'" type="button">Edit</button>
                    <button class="btn btn-danger" onclick="location.href='{% url 'books:books_delete' books.id %}'" type="button">Delete</button>
                    
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <br>
        
        <button class="btn btn-success" onclick="location.href='{% url 'books:books_new' %}'" type="button">Add New Button</button>
        
</body>